"""removed description fom the cartegory

Revision ID: 00aa6302f0a4
Revises: 7987e6aa0600
Create Date: 2024-08-15 04:25:30.290967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00aa6302f0a4'
down_revision = '7987e6aa0600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
